# Generated by Django 4.0.3 on 2022-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forbiddenword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
