# Generated by Django 3.2.12 on 2022-03-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_comment'),
        ('blog_app', '0006_delete_user'),
    ]

    operations = [
    ]
