# Generated by Django 4.0.3 on 2022-03-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_post_comment_number'),
        ('blog_app', '0010_post_dislikes'),
    ]

    operations = [
    ]
