# Generated by Django 3.2.12 on 2022-03-30 11:50

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0011_merge_0010_post_comment_number_0010_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriptions',
            field=models.ManyToManyField(related_name='category_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
